### ISSUE TITLE
git.io url redirection service deprecated

### ISSUE THREAD

**Issue by ghost** [christopherball/christopherball.github.io#1]
Per the [announcement](https://github.blog/changelog/2022-04-25-git-io-deprecation/): Git.io is now read only, breaking the Generate Short Link function in the Ascii Math Formula Editor.

Thank you for the Ascii Math Formula Editor. A great help in my recent studies.

**Comment by christopherball** [comment]
I've gone ahead and updated it to a different one that currently appears to not require any sort of sign up and is free.  Glad to hear the tool has been helpful, beats typing native LaTeX ;).
